/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mazarini.resa.data.network.model.travelplanner.unverified


import com.squareup.moshi.Json

/**
 * A subset of TransportMode
 *
 * Values: vasttagen,longdistancetrain,regionaltrain
 */

enum class VTApiPlaneraResaWebV4ModelsJourneyTransportSubMode(val value: kotlin.String) {

    @Json(name = "vasttagen")
    vasttagen("vasttagen"),

    @Json(name = "longdistancetrain")
    longdistancetrain("longdistancetrain"),

    @Json(name = "regionaltrain")
    regionaltrain("regionaltrain");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is VTApiPlaneraResaWebV4ModelsJourneyTransportSubMode) "$data" else null

        /**
         * Returns a valid [VTApiPlaneraResaWebV4ModelsJourneyTransportSubMode] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): VTApiPlaneraResaWebV4ModelsJourneyTransportSubMode? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

