/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.mazarini.resa.data.network.model.travelplanner.unverified


import com.squareup.moshi.Json

/**
 * Information about the error.
 *
 * @param errorCode Error code.
 * @param errorMessage More detailed description of the error.
 */


data class VTApiPlaneraResaWebV4ModelsApiError (

    /* Error code. */
    @Json(name = "errorCode")
    val errorCode: kotlin.Int? = null,

    /* More detailed description of the error. */
    @Json(name = "errorMessage")
    val errorMessage: kotlin.String? = null

)

