/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.resa.data.network.model.unverified


import com.squareup.moshi.Json

/**
 * The different kinds of detailed information that could be included in a get departure details request.
 *
 * Values: servicejourneycalls,servicejourneycoordinates,occupancy
 */

enum class VTApiPlaneraResaWebV4ModelsDepartureDetailsIncludeType(val value: kotlin.String) {

    @Json(name = "servicejourneycalls")
    servicejourneycalls("servicejourneycalls"),

    @Json(name = "servicejourneycoordinates")
    servicejourneycoordinates("servicejourneycoordinates"),

    @Json(name = "occupancy")
    occupancy("occupancy");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is VTApiPlaneraResaWebV4ModelsDepartureDetailsIncludeType) "$data" else null

        /**
         * Returns a valid [VTApiPlaneraResaWebV4ModelsDepartureDetailsIncludeType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): VTApiPlaneraResaWebV4ModelsDepartureDetailsIncludeType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

