/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.resa.data.network.model.unverified


import com.squareup.moshi.Json

/**
 * Information specifying the interval when valid journey information is available, i.e. when it is possible to search journeys.
 *
 * @param validFrom The start time of the interval when valid journey information is available, specified in RFC 3339 format.
 * @param validUntil The end time of the interval when valid journey information is available, specified in RFC 3339 format.
 */


data class VTApiPlaneraResaWebV4ModelsValidTimeIntervalApiModel (

    /* The start time of the interval when valid journey information is available, specified in RFC 3339 format. */
    @Json(name = "validFrom")
    val validFrom: kotlin.String? = null,

    /* The end time of the interval when valid journey information is available, specified in RFC 3339 format. */
    @Json(name = "validUntil")
    val validUntil: kotlin.String? = null

)

