/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.resa.data.network.model.unverified


import com.squareup.moshi.Json

/**
 * A subset of LocationType
 *
 * Values: stoparea,stoppoint,pointofinterest,metastation
 */

enum class VTApiPlaneraResaWebV4ModelsLocationByCoordinatesType(val value: kotlin.String) {

    @Json(name = "stoparea")
    stoparea("stoparea"),

    @Json(name = "stoppoint")
    stoppoint("stoppoint"),

    @Json(name = "pointofinterest")
    pointofinterest("pointofinterest"),

    @Json(name = "metastation")
    metastation("metastation");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is VTApiPlaneraResaWebV4ModelsLocationByCoordinatesType) "$data" else null

        /**
         * Returns a valid [VTApiPlaneraResaWebV4ModelsLocationByCoordinatesType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): VTApiPlaneraResaWebV4ModelsLocationByCoordinatesType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

