package com.mazarini.resa.ui.theme.colors

import androidx.compose.ui.graphics.Color

internal val DarkColorPalette = ResaColors(
    background = Black900,
    surface = ChimneySweep,
    surfaceBlur = ChimneySweep_90,
    primary = Blue400,
    graph = Graphics(
        active = White_95,
        normal = White_75,
        disabled = White_50,
        detail = White_35,
        soft = White_20,
        minimal = White_10,
    ),

    secondary = Yellow400,
    textPrimary = Color.White,
    textSecondary = Color(0x80FFFFFF),
    textTertiary = Black400,
    alert = Color.Red,
    icon = Yellow700,
    iconBackground = Yellow700_10,
    btnBackground = Black700,
    btnSecondaryBkg = Color.Black,
    btnTertiaryBkg = White_95,
    lightDetail = White_20,
    lightText = Color.Black,
    ultraLightDetail = Color.Black,
    separatorLight = Color.Black,
    shimmer = Color.LightGray,
    warningLow = GoldenBrown,
    warningMedium = Tangelo,
    warningHigh = MahoganyDark,
    warningLowBg = FieldDrab,
    warningMediumBg = Sienna,
    warningHighBg = SealBrown,
    trackingBg = Color(0xFF144104),
    trackingOutline = Color(0xFF287A0B),
)

internal val LightColorPalette = ResaColors(
    background = Color.White,
    surface = Color.White,
    surfaceBlur = Black900_85,
    primary = Blue500,
    graph = Graphics(
        active = White_95,
        normal = Black900_65,
        disabled = Black900_35,
        detail = Black900_20,
        soft = White_35,
        minimal = Black900_05,
    ),

    secondary = Yellow400,
    textPrimary = Color(0xFF000C1A),
    textSecondary = Black900_85,
    textTertiary = Black400,
    alert = Color.Red,
    icon = Yellow700,
    iconBackground = Yellow700_10,
    btnBackground = Black900_4,
    btnSecondaryBkg = White_35,
    btnTertiaryBkg = White_95,
    lightDetail = Black900_20,
    lightText = Black900_75,
    ultraLightDetail = Black900_3,
    separatorLight = Black900_8,
    shimmer = Color.LightGray,
    warningLow = TangerineYellow,
    warningMedium = AtomicTangerine,
    warningHigh = Mahogany,
    warningLowBg = EarlyDawn,
    warningMediumBg = Serenade,
    warningHighBg = FairPink,
    trackingBg = LightYellowGreen,
    trackingOutline = YellowGreen,
)
